"""
文件过滤器

过滤不需要参与检测的文件和目录。

Author: GitHub 项目代码相似度检测工具
"""

from typing import Set, List, Optional
from pathlib import Path
from fnmatch import fnmatch


class FileFilter:
    """文件过滤器
    
    根据配置规则过滤文件。支持 .ghsimignore 规则文件。
    """
    
    LANGUAGE_EXTENSIONS = {
        'python': {'.py', '.pyw'},
        'java': {'.java'},
        'javascript': {'.js', '.jsx'},
        'typescript': {'.ts', '.tsx'},
        'ts': {'.ts', '.tsx'},
        'go': {'.go'},
        'rust': {'.rs'},
        'c': {'.c', '.h'},
        'cpp': {'.cpp', '.hpp', '.cc', '.cxx'},
    }
    
    DEFAULT_EXCLUDE_DIRS = {
        'node_modules', 'venv', '.git', '__pycache__',
        'dist', 'build', '.idea', 'target', 'vendor',
        '.vscode', '.github', 'tests', 'test', 'docs',
        'env', '.env', 'site-packages', '.tox', 'eggs',
        '.eggs', 'lib', 'lib64', 'parts', 'sdist', 'var',
        'wheels', '*.egg-info', 'bin', 'include',
        'bower_components', '.bundle', 'Pods', 'Carthage',
        'third_party', 'thirdparty', '3rdparty', 'deps',
        'dependencies', 'packages', 'submodules',
        '.gradle', '.m2', '.nuget', '.cargo', '.rustup',
        'generated', 'autogenerated', '.semgrep',
    }
    
    DEFAULT_EXCLUDE_PATTERNS = [
        '*.min.js', '*.min.css', '*.test.*', '*.spec.*',
        'package-lock.json', 'yarn.lock', 'poetry.lock',
        'setup.py', 'setup.cfg', 'requirements*.txt',
        '*.md', '*.rst', '*.txt', '*.json', '*.yaml', '*.yml',
        '*.png', '*.jpg', '*.gif', '*.svg', '*.ico',
        '*.pyc', '*.pyo', '*.class', '*.jar', '*.war',
        '*.o', '*.so', '*.dll', '*.dylib', '*.wasm',
        '*.proto', '*.pb.go', '*.generated.*',
        'Makefile', 'Dockerfile', '.dockerignore',
        '.gitignore', '.gitattributes', 'LICENSE', 'COPYING',
        'Gemfile.lock', 'Pipfile.lock', 'pnpm-lock.yaml',
        'gradlew', 'mvnw', '*.gradle', '*.xml',
    ]
    
    def __init__(
        self,
        exclude_dirs: Optional[Set[str]] = None,
        exclude_patterns: Optional[List[str]] = None,
        languages: Optional[List[str]] = None,
        ignore_file_path: Optional[str] = None
    ):
        """初始化文件过滤器
        
        Args:
            exclude_dirs: 排除目录集合
            exclude_patterns: 排除文件模式列表
            languages: 支持的语言列表
            ignore_file_path: .ghsimignore 文件路径
        """
        self.exclude_dirs = exclude_dirs or self.DEFAULT_EXCLUDE_DIRS
        self.exclude_patterns = exclude_patterns or self.DEFAULT_EXCLUDE_PATTERNS
        self.languages = languages or ['python']
        self._ignore_patterns: List[str] = []
        if ignore_file_path:
            self._load_ignore_file(ignore_file_path)
    
    def _load_ignore_file(self, ignore_file_path: str) -> None:
        """加载 .ghsimignore 规则文件
        
        每行一条规则，支持 glob 模式。# 开头为注释，! 开头为反排除。
        """
        path = Path(ignore_file_path)
        if not path.exists():
            return
        with open(path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                self._ignore_patterns.append(line)
    
    def should_include(self, file_path: str) -> bool:
        """判断文件是否应该参与检测
        
        Args:
            file_path: 文件路径
        
        Returns:
            是否应该包含
        """
        path = Path(file_path)
        
        for exclude_dir in self.exclude_dirs:
            if f'/{exclude_dir}/' in f'/{file_path}/':
                return False
            if path.parts and path.parts[0] == exclude_dir:
                return False
        
        filename = path.name
        for pattern in self.exclude_patterns:
            if fnmatch(filename, pattern):
                return False
        
        if self._ignore_patterns:
            included = True
            for pattern in self._ignore_patterns:
                if pattern.startswith('!'):
                    if fnmatch(file_path, pattern[1:]) or fnmatch(filename, pattern[1:]):
                        included = True
                else:
                    if fnmatch(file_path, pattern) or fnmatch(filename, pattern):
                        included = False
            if not included:
                return False
        
        ext = path.suffix
        valid_extensions = set()
        for lang in self.languages:
            valid_extensions.update(self.LANGUAGE_EXTENSIONS.get(lang, set()))
        
        return ext in valid_extensions
    
    def get_language(self, file_path: str) -> Optional[str]:
        """根据文件扩展名判断语言
        
        Args:
            file_path: 文件路径
        
        Returns:
            语言名称，无法识别返回 None
        """
        ext = Path(file_path).suffix
        
        for lang in self.languages:
            if ext in self.LANGUAGE_EXTENSIONS.get(lang, set()):
                return lang
        
        return None
    
    def is_code_file(self, file_path: str) -> bool:
        """判断是否为代码文件
        
        Args:
            file_path: 文件路径
        
        Returns:
            是否为代码文件
        """
        return self.get_language(file_path) is not None
